In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/oekpom/Desktop/Datasets/Machine Learning/Lesson 10/ratings.csv")

In [4]:
df

       userId  movieId  rating   timestamp
0           1        1     4.0   964982703
1           1        3     4.0   964981247
2           1        6     4.0   964982224
3           1       47     5.0   964983815
4           1       50     5.0   964982931
5           1       70     3.0   964982400
6           1      101     5.0   964980868
7           1      110     4.0   964982176
8           1      151     5.0   964984041
9           1      157     5.0   964984100
10          1      163     5.0   964983650
11          1      216     5.0   964981208
12          1      223     3.0   964980985
13          1      231     5.0   964981179
14          1      235     4.0   964980908
15          1      260     5.0   964981680
16          1      296     3.0   964982967
17          1      316     3.0   964982310
18          1      333     5.0   964981179
19          1      349     4.0   964982563
20          1      356     4.0   964980962
21          1      362     5.0   964982588
22          1      367     4.0   964981710
23          1      423     3.0   964982363
24          1      441     4.0   964980868
25          1      457     5.0   964981909
26          1      480     4.0   964982346
27          1      500     3.0   964981208
28          1      527     5.0   964984002
29          1      543     4.0   964981179
...       ...      ...     ...         ...
77835     610     6548     3.0  1493846789
77836     610     6567     3.0  1493849834
77837     610     6595     3.5  1493847505
77838     610     6615     3.0  1493848161
77839     610     6617     3.5  1493849964
77840     610     6618     4.5  1493847261
77841     610     6620     4.0  1493845340
77842     610     6686     1.0  1479542333
77843     610     6707     3.5  1493848170
77844     610     6708     3.5  1493847441
77845     610     6709     3.5  1493846114
77846     610     6711     5.0  1493845008
77847     610     6731     4.0  1495959036
77848     610     6734     2.0  1479543143
77849     610     6754     3.0  1493846017
77850     610     6755     4.0  1493847312
77851     610     6764     3.0  1493846886
77852     610     6807     4.5  1479543348
77853     610     6820     4.0  1493848224
77854     610     6863     4.5  1479542813
77855     610     6867     4.0  1493847197
77856     610     6872     1.0  1493848358
77857     610     6873     3.0  1479544373
77858     610     6874     4.5  1493844709
77859     610     6934     3.5  1493845393
77860     610     6936     3.5  1493847813
77861     610     6942     3.5  1493845063
77862     610     6947     4.0  1493846749
77863     610     6957     4.5  1493845299
77864     610     6966     4.0  1479542691

[77865 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split
n_users = df.userId.unique().shape[0]
n_movies = df.movieId.unique().shape[0]
train_data, test_data = train_test_split(df,test_size=0.25)

In [6]:
train_data_matrix = np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    try:
        train_data_matrix[line[1]-1,line[2]-1] = line[3]
    except:
        continue
train_data_matrix

array([[4. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 2. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [7]:
test_data_matrix = np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    try:
        test_data_matrix[line[1]-1,line[2]-1] = line[3]
    except:
        continue
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff = (train_data_matrix - mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.10456684,  0.51921382,  0.30358444, ...,  0.08229969,
         0.08500318,  0.0778425 ],
       [ 1.01590948,  0.41048135,  0.18528073, ..., -0.04768408,
        -0.04538851, -0.05270324],
       [ 1.01827205,  0.41778846,  0.19176779, ..., -0.04037488,
        -0.03787694, -0.04527446],
       ...,
       [ 1.24296185,  0.65112364,  0.45172248, ...,  0.23195838,
         0.23499772,  0.22764455],
       [ 0.99880604,  0.40768959,  0.19477565, ..., -0.03159268,
        -0.02931273, -0.03664436],
       [ 1.17198495,  0.59270312,  0.38367118, ...,  0.14938996,
         0.15185025,  0.14504296]])

In [9]:
n_users

610